/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DeviceStatus (
  /* Last status date (AIO, AIO+, Box, Extender, OutdoorSiren, Pir, Remote, Siren, Tag). */
  lastStatusAt: Option[DateTime],
  /* rLink Quality (AIO, AIO+, Camera, Extender, OutdoorSiren, Pir, Remote, Siren, Tag). */
  rlinkQuality: Option[Int],
  /* rLink Quality Percent (AIO, AIO+, Camera, Extender, OutdoorSiren, Pir, Siren, Tag). */
  rlinkQualityPercent: Option[Int],
  /* Level of battery (AIO+, Box, OutdoorSiren, Pir, Remote, Siren, Tag). */
  batteryLevel: Option[Int],
  /* Is device lost ? (Extender, OutdoorSiren, Pir, Remote, Siren, Tag). */
  deviceLost: Option[Boolean],
  /* Power mode (AIO, AIO+, Box, Camera, Extender). */
  powerMode: Option[DeviceStatusEnums.PowerMode],
  /* Time of last online (AIO, AIO+, Box, Camera). */
  lastOnlineAt: Option[DateTime],
  /* Time of last offline (AIO, AIO+, Box, Camera). */
  lastOfflineAt: Option[DateTime],
  /* Level of wifi signal (AIO, AIO+, Box, Camera). */
  wifiLevel: Option[Int],
  /* Wifi Level Percent (AIO, AIO+, Box, Camera). */
  wifiLevelPercent: Option[Int],
  /* Power state (AIO, AIO+, Box). */
  powerState: Option[Int],
  /* mfa Quality Percent (AIO, AIO+, Box). */
  mfaQualityPercent: Option[Int],
  /* Last myfox around test (AIO, AIO+, Box). */
  mfaLastTestAt: Option[DateTime],
  /* Last myfox around test success (AIO, AIO+, Box). */
  mfaLastTestSuccessAt: Option[DateTime],
  /* Last MFA online status (AIO, AIO+, Box). */
  mfaLastOnlineAt: Option[DateTime],
  /* Last MFA ofline status (AIO, AIO+, Box). */
  mfaLastOfflineAt: Option[DateTime],
  /* Last MFA connected status (AIO, AIO+, Box). */
  mfaLastConnectedAt: Option[DateTime],
  /* Last MFA disconnected status (AIO, AIO+, Box). */
  mfaLastDisconnectedAt: Option[DateTime],
  /* Shutter state (AIO, AIO+, Camera). */
  shutterState: Option[DeviceStatusEnums.ShutterState],
  /* Last shutter opened (AIO, AIO+, Camera). */
  lastShutterOpenedAt: Option[DateTime],
  /* Last shutter closed (AIO, AIO+, Camera). */
  lastShutterClosedAt: Option[DateTime],
  /* rLink state (Remote, Siren, Tag). */
  rlinkState: Option[Int],
  /* Lorawan Quality Percent (AIO+, Box). */
  loraQualityPercent: Option[Int],
  /* Last LoraWan test (AIO+, Box). */
  loraLastTestAt: Option[DateTime],
  /* Last LoraWan success test (AIO+, Box). */
  loraLastTestSuccessAt: Option[DateTime],
  /* Last LoraWan online status (AIO+, Box). */
  loraLastOnlineAt: Option[DateTime],
  /* Last LoraWan offline status (AIO+, Box). */
  loraLastOfflineAt: Option[DateTime],
  /* Last LoraWan connected status (AIO+, Box). */
  loraLastConnectedAt: Option[DateTime],
  /* Last LoraWan disconnected status (AIO+, Box). */
  loraLastDisconnectedAt: Option[DateTime],
  /* Temperature (Pir, OutdoorSiren). */
  temperature: Option[Float],
  /* Time of last temperature (OutdoorSiren, Pir). */
  temperatureAt: Option[DateTime],
  /* FSK Level (Box). */
  fskLevel: Option[Int],
  /* BLE Level (Box). */
  bleLevel: Option[Int],
  /* Battery status (Extender). */
  batteryStatus: Option[Int],
  /* Time of outdoor siren installation (OutdoorSiren). */
  mountedAt: Option[DateTime],
  /* Is battery low (Pir). */
  batteryLow: Option[Boolean],
  /* Remote battery level state (Remote). */
  batteryLevelState: Option[Int],
  /* Remote keep alive (Remote). */
  keepAlive: Option[Int],
  /* Last check in from remote (Remote). */
  lastCheckInState: Option[DateTime],
  /* Last check out from remote (Remote). */
  lastCheckOutState: Option[DateTime],
  /* Is Tag recalibration required (Tag). */
  recalibrationRequired: Option[Boolean],
  /* Is Tag can be recalibrate (Tag). */
  recalibrateable: Option[Boolean],
  /* Is Tag cover present (Tag). */
  coverPresent: Option[Boolean]
) extends ApiModel

object DeviceStatusEnums {

  type PowerMode = PowerMode.Value
  type ShutterState = ShutterState.Value
  object PowerMode extends Enumeration {
    val Battery = Value("battery")
    val Current = Value("current")
  }

  object ShutterState extends Enumeration {
    val Opened = Value("opened")
    val Closed = Value("closed")
  }

}

