/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DeviceDefinition (
  /* The device definition unique identifier */
  deviceDefinitionId: Option[DeviceDefinitionEnums.DeviceDefinitionId],
  /* The device label */
  label: String,
  /* The device type */
  `type`: DeviceDefinitionEnums.&#x60;Type&#x60;
) extends ApiModel

object DeviceDefinitionEnums {

  type DeviceDefinitionId = DeviceDefinitionId.Value
  type &#x60;Type&#x60; = &#x60;Type&#x60;.Value
  object DeviceDefinitionId extends Enumeration {
    val MssCamera = Value("mss_camera")
    val MssPlug = Value("mss_plug")
    val MssRemote = Value("mss_remote")
    val MssSiren = Value("mss_siren")
    val MssOutdoorSiren = Value("mss_outdoor_siren")
    val MssTag = Value("mss_tag")
    val MssCameraMyfox1 = Value("mss_camera_myfox_1")
    val MssAio1Plus = Value("mss_aio_1_plus")
    val MssAio1 = Value("mss_aio_1")
    val SpIndoorCam1 = Value("sp_indoor_cam1")
  }

  object &#x60;Type&#x60; extends Enumeration {
    val Box = Value("box")
    val Camera = Value("camera")
    val Remote = Value("remote")
    val Siren = Value("siren")
    val Tag = Value("tag")
  }

}

