/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class SiteDiagnosis (
  mainStatus: Option[SiteDiagnosisEnums.MainStatus],
  mainMessage: Option[String],
  mainMessageVars: Option[Seq[String]],
  deviceDiagnosisAvailable: Option[Boolean],
  deviceDiagnosisExpired: Option[Boolean],
  items: Option[Seq[SiteDiagnosisItem]]
) extends ApiModel

object SiteDiagnosisEnums {

  type MainStatus = MainStatus.Value
  object MainStatus extends Enumeration {
    val Ok = Value("ok")
    val DeviceOffline = Value("device-offline")
    val DeviceWarning = Value("device-warning")
  }

}

